version: '2'

services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'heat'
      POSTGRES_PASSWORD: 'reviveit'
      TZ: "America/Chicago"
    ports:
      - '5434:5432'
    volumes:
      - 'postgresql:/var/lib/postgresql/data'
      - '.:/Heat'
  
  frontend:
    depends_on:
      - 'database'
    build: .
    ports:
      - '3001:3030'
    volumes:
      - '.:/Heat'
    env_file:
      - '.env'
    environment:
      TZ: "America/Chicago"
volumes:
  postgresql:
