production:
  key: <%= ENV["SECRET_KEY_BASE"] %>
  admins:
  - keaton.burleson@er2.com
  - harold.schreckengost@er2.com
  - doug.green@er2.com
  - kaelin@er2.com
  - kaelin.jacobson@er2.com
  supervisors:
  - kaelin@er2.com
  - kaelin.jacobson@er2.com
  - test@me.com
  - doug.green@er2.com
  - kipp.hunter@er2.com
development:
  key: test
  supervisors:
  - test@me.com
  admins:
  - test@me.com
